import Link from "next/link";
import "./globals.css";
import Image from "next/image";
import avatar from "./avatar.jpg";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
// import { Analytics } from "@/components/analytics";
import { ModeToggle } from "@/components/mode-toggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-50 ${inter.className}`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="max-w-5xl mx-auto py-10 px-4">
            <header>
              <div className="flex items-center justify-between">
                <div className="flex items-center">
                  {" "}
                  <Link href="/">
                    <Image
                      src={avatar}
                      alt="ashutosh-avatar"
                      className="rounded-full grayscale"
                      placeholder="blur"
                      width={50}
                      priority
                    />
                  </Link>
                  <nav className="text-sm font-medium space-x-6 ml-8">
                    <Link href="/projects">Projects</Link>
                    <Link href="/blog">Blog</Link>
                  </nav>
                </div>
                <ModeToggle />
              </div>
            </header>
            <main>{children}</main>
          </div>
          {/* <Analytics /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
